version: '3.9'

services:
    react:
        image: node:20-alpine3.19
        build:
            context: ./frontend
            dockerfile: ui.dockerfile
        ports:
            - 3000:5173
        volumes:
            - ./frontend:/app/
            - /app/node_modules
        networks:
            - react
    api:
        image: golang:1.22-alpine3.19
        build:
            context: ./api
            dockerfile: api.dockerfile
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
        networks:
            - api
        hostname: localhost
        depends_on:
            - db
    db:
        container_name: db
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports:
        - "5432:5432"
        volumes:
        - pgdata:/var/lib/postgresql/data

networks:
    api:
    react:

volumes:
    pgdata: {}
